### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Kadantte** [LidaIO/reader#4]
Any update about this Project, it's been a while Ash I hope you're doing well :3

**Comment by Kadantte** [comment]
Well, it was year since I opened this I think it's time to close it :p.

**Comment by ash123456789** [comment]
@Kadantte This project has been moved to a private repository on my account, and has been renamed to Genkan. I'm planning on releasing an open source version under [this](https://github.com/genkan-org) organisation in the near future. In the meantime you can join the [discord](https://discord.gg/aQYthDj) server for updates to the project.

**Comment by Kadantte** [comment]
Yea I already have seen the Genkan project [ Psycho Play website ] and I love it you did a great job on it.
